name: "Import checker"

on:
  - push

jobs:
  isort-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install isort
      run: |
        pip install -U pip
        pip install isort
    - name: Run isort
      run: isort . --settings-path .isort.cfg